project:
  type: book
  output-dir: "docs/"
  resources:
    - "cover.png"
    - "slides/*.html"
    - "slides/*_files/"
    - "slides/images/"
  # render: 
  #   - "!materiais/"  
  
book:
  title: "Relatórios reprodutíveis com R (2025)"
  description: "Página do curso de verão oferecido pelo IME/USP, 2025."
  repo-url: "https://github.com/beatrizmilz/2025-curso-de-verao-ime-usp-relatorios"  
  author: "Beatriz Milz"
  date: "1/14/2025"
  date-format: "MMMM [de] YYYY"
  cover-image: "cover.png"
  chapters:
    - part: "Pré-curso"
      chapters:
      - index.qmd
      - plataforma-usp.qmd
      - instalacoes-pre-curso.qmd
      - trabalho-final.qmd
    - part: "Materiais"
      chapters:
      - slides.qmd
#    - referencias.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    footer: "[Relatórios reprodutíveis com R (2025) - Programa de Verão IME-USP](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/)."

lang: pt
code-link: true


