---
title: "Materiais por aula"
---

## Revisão de conceitos úteis

-   [O que é o R?](https://www.instagram.com/p/C2DDu-MLZ4W/)

-   [O que é o RStudio?](https://www.instagram.com/p/C2IJPYqLjIe/)

-   [Versões gratuitas do RStudio](https://www.instagram.com/p/C2Xh63gLWIM/?img_index=4)

- [O que é o tidyverse?](https://www.instagram.com/p/C2fQI7FrlC2/?img_index=1)

## Scripts de práticas em aula

- [Acesse os arquivos separadamente](https://github.com/beatrizmilz/2025-curso-de-verao-ime-usp-relatorios/tree/main/scripts-aula)

- [Baixe o repositório do GitHub (`.zip`)](https://github.com/beatrizmilz/2025-curso-de-verao-ime-usp-relatorios/archive/refs/heads/main.zip)

## Slides

-   [Introdução ao Curso](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides/01-intro-curso.html)

-   [Introdução ao Quarto](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides/02-intro-quarto.html)

-   [Introdução ao conceito de reprodutibilidade](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides/03-reprodutibilidade.html)

-   [Elementos úteis para relatórios acadêmicos](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides/04-elementos-acad.html)

-   [Relatórios com parâmetros](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides/05-parametros.html)


<!-- -   [Feedbacks - Trabalho final](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides/06-feedback-trabalho-final.html) -->

## Para revisar, consultar e ir além!

- [Documentação do Quarto](https://quarto.org/)

- [Livro R para Ciência de Dados (2ed)](https://pt.r4ds.hadley.nz/) por Hadley Wickham, Mine Çetinkaya-Rundel, e Garrett Grolemund.
  - [Comunicar: Quarto](https://pt.r4ds.hadley.nz/quarto.html)
  - [Comunicar: Formatos para Quarto](https://pt.r4ds.hadley.nz/quarto-formats.html)  

- [Livro Zen do R (por Caio Lente + Curso-R)](https://curso-r.github.io/zen-do-r/):
  - [.RData e .Rhistory](https://curso-r.github.io/zen-do-r/rdata-rhistory.html)
  - [Rproj e diretórios](https://curso-r.github.io/zen-do-r/rproj-dir.html)
  - [Git e GitHub](https://curso-r.github.io/zen-do-r/git-github.html)

- Material do curso "R intermediário e pesquisa reprodutível" ministrado por Beatriz Milz
  - [Reprodutibilidade e estruturação de projeto](https://ipeadata-lab.github.io/curso_r_intermediario_202501/reprodutibilidade.html)
  - [Produção de relatórios com Quarto](https://ipeadata-lab.github.io/curso_r_intermediario_202501/relatorios.html)
  - [Introdução ao controle de versão com Git e GitHub](https://ipeadata-lab.github.io/curso_r_intermediario_202501/git-github.html)
  - [Programação funcional](https://ipeadata-lab.github.io/curso_r_intermediario_202501/programacao-funcional.html)
  
- Material do workshop [Introdução à GitHub para pesquisadores](https://git4researchers-latinr2024.netlify.app/) (em espanhol), por Beatriz Milz e Yanina Bellini.
  

## Materiais antigos

-   [Introdução ao RMarkdown](https://beatrizmilz.github.io/2025-curso-de-verao-ime-usp-relatorios/slides/extra-1-intro-rmarkdown.html)




